import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseProvider } from "./components/providers/SupabaseProvider";
import Header from "./components/Header";
import QueryProvider from "./components/providers/QueryProvider";
import ReduxProvider from "./components/providers/ReduxProvider";
import UserDataProvider from "./components/providers/UserDataProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Calculation Helper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <QueryProvider>
            <SupabaseProvider>
              <UserDataProvider>
                <Header />
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                  {children}
                </main>
              </UserDataProvider>
            </SupabaseProvider>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
